//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrianow_backers_3isp9_18.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientAccount()
        {
            this.Purchase = new HashSet<Purchase>();
        }
    
        public int IdClient { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public Nullable<int> Age { get; set; }
        public string CodeGender { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}
