//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrianow_backers_3isp9_18.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.BuyProduct = new HashSet<BuyProduct>();
        }
    
        public int IdBuy { get; set; }
        public int IdClient { get; set; }
        public System.DateTime DateTime { get; set; }
        public int IdStaff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyProduct> BuyProduct { get; set; }
        public virtual ClientAccount ClientAccount { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
