//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrianow_backers_3isp9_18.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int IdSupply { get; set; }
        public string FirmTitle { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Quantity { get; set; }
        public int Cost { get; set; }
        public int IdProduct { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
